### ISSUE TITLE
Rewind at MouseOut

### ISSUE THREAD

**Issue by SchmidtDEN** [biohzrdmx/jQuery.hoverPlay#2] opened 2022-03-17 13:58 UTC
Hi biohzrdmx

Thanks for a really cool piece of code that works awesome. 
Out of curiosity; Would it be possible to have the video go to the beginning (0 seconds) on mouseout? :) 

Thanks again for a great piece of code :)

**Comment by biohzrdmx** [comment] 2022-03-17 17:50
Hi SchmidtDEN, thanks for using this plugin; although rewinding the video is not built-in, it can be done easily with a callback:

```javascript
$.extend(true, $.hoverPlay.defaults, {
  callbacks: {
    pause: function(el,  video) {
      video.pause();
      video.currentTime = 0;
    }
  }
});
```

That way you may also add a custom class or do extra DOM manipulation should you want to: https://github.com/biohzrdmx/jQuery.hoverPlay#advanced-usage

There are three callbacks available, `play` that occurs on mouse over and after the specified delay, `pause` that occurs on mouse out and after its corresponding delay and finally `click` that triggers on mouse click.

Hope this answers you question and thanks again for reaching out.

Regards.

**Comment by SchmidtDEN** [comment] 2022-03-17 19:05
B-e-a-utiful! 

Works like a charm. 
Thanks for the quick reply, really appreciate that :) 

All the best :)

**Comment by biohzrdmx** [comment] 2022-03-17 19:30
Happy to know that it works as intended, I'm closing the issue now.

Regards.

**Closed as completed by biohzrdmx** 2022-03-17 19:30 UTC
